services:
 db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=newslydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - newsly-network
    ports:
      - "5432:5432"

networks:
  newsly-network:
    driver: bridge

volumes:
  postgres-data:

